services:
  consul:
    image: hashicorp/consul:latest
    container_name: smart-travel-consul
    ports:
      - "8500:8500"
    command: "agent -dev -client=0.0.0.0"

  kafka:
    image: apache/kafka:latest
    container_name: smart-travel-kafka
    hostname: kafka
    ports:
      - "9094:9094"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 1

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: smart-travel-kafka-ui
    ports:
      - "8085:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: smart-travel-kafka
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    depends_on:
      - kafka

  recommendation-db:
    image: postgres:16
    container_name: smart-travel-recommendation-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: recommendation_db
      POSTGRES_USER: recommendation_user
      POSTGRES_PASSWORD: recommendation_pass
    volumes:
      - recommendation_data:/var/lib/postgresql/data

  trip-db:
    image: postgres:16
    container_name: smart-travel-trip-db
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: trip_db
      POSTGRES_USER: trip_user
      POSTGRES_PASSWORD: trip_pass
    volumes:
      - trip_data:/var/lib/postgresql/data

volumes:
  recommendation_data:
  trip_data: