spring.application.name=trip-service
server.port=8081

spring.cloud.consul.host=consul
spring.cloud.consul.port=8500
spring.cloud.consul.discovery.service-name=trip-service
spring.cloud.consul.discovery.register=true
spring.cloud.consul.discovery.prefer-ip-address=true
spring.cloud.consul.discovery.health-check-url=http://trip-service:8081/actuator/health

management.endpoints.web.exposure.include=health,info

spring.datasource.url=jdbc:postgresql://trip-db:5432/trip_db
spring.datasource.username=trip_user
spring.datasource.password=trip_pass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.producer.acks=all
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

app.kafka.topics.trip-created=trip-created

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8086/realms/smart-travel
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8080/realms/smart-travel/protocol/openid-connect/certs