spring.application.name=recommendation-service
server.port=8082

spring.cloud.consul.host=localhost
spring.cloud.consul.port=8500
spring.cloud.consul.discovery.service-name=recommendation-service
spring.cloud.consul.discovery.register=true
spring.cloud.consul.discovery.prefer-ip-address=true
spring.cloud.consul.discovery.health-check-url=http://host.docker.internal:8082/actuator/health

management.endpoints.web.exposure.include=health,info

spring.datasource.url=jdbc:postgresql://localhost:5433/recommendation_db
spring.datasource.username=recommendation_user
spring.datasource.password=recommendation_pass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.kafka.bootstrap-servers=localhost:9094

spring.kafka.consumer.group-id=recommendation-service-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

app.kafka.topics.trip-created=trip-created

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8086/realms/smart-travel