spring.application.name=recommendation-service
server.port=8082

spring.cloud.consul.host=${CONSUL_HOST:localhost}
spring.cloud.consul.port=${CONSUL_PORT:8500}
spring.cloud.consul.discovery.service-name=recommendation-service
spring.cloud.consul.discovery.register=true
spring.cloud.consul.discovery.prefer-ip-address=true
spring.cloud.consul.discovery.health-check-url=${CONSUL_HEALTH_CHECK_URL:http://host.docker.internal:8082/actuator/health}

management.endpoints.web.exposure.include=health,info

spring.datasource.url=${RECOMMENDATION_DB_URL:jdbc:postgresql://localhost:5433/recommendation_db}
spring.datasource.username=${RECOMMENDATION_DB_USERNAME:recommendation_user}
spring.datasource.password=${RECOMMENDATION_DB_PASSWORD:recommendation_pass}

spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9094}
spring.kafka.consumer.group-id=${KAFKA_CONSUMER_GROUP_ID:recommendation-service-group}
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

app.kafka.topics.trip-created=${TRIP_CREATED_TOPIC:trip-created}

spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER_URI:http://localhost:8086/realms/smart-travel}

external.geoapify.enabled=${GEOAPIFY_ENABLED:true}
external.geoapify.api-key=${GEOAPIFY_API_KEY:}
external.geoapify.geocoding-url=${GEOAPIFY_GEOCODING_URL:https://api.geoapify.com/v1/geocode/search}
external.geoapify.places-url=${GEOAPIFY_PLACES_URL:https://api.geoapify.com/v2/places}
external.geoapify.radius-meters=${GEOAPIFY_RADIUS_METERS:5000}
external.geoapify.limit=${GEOAPIFY_LIMIT:10}