### 1. Get Keycloak access token
POST http://localhost:8086/realms/smart-travel/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=smart-travel-client&username=demo-user&password=demo-pass&grant_type=password

> {%
    client.global.set("access_token", response.body.access_token);
%}


### 2. Security negative test - should return 401 without token
GET http://localhost:8080/api/trips


### 3. Test protected trips endpoint with token
GET http://localhost:8080/api/trips
Authorization: Bearer {{access_token}}


### 4. Test protected recommendations endpoint with token
GET http://localhost:8080/api/recommendations?destination=Paris&type=ATTRACTION
Authorization: Bearer {{access_token}}